version: '3.8'
services:
  registry:
    image: eclipsebasyx/aas-registry:1.0.2
    environment:
        - BaSyxRegistry_registry.backend=InMemory
        - BaSyxContext_contextPath=/registry
        - BaSyxContext_contextPort=4000
    container_name: registry
    ports:
      - 4000:4000

  aas:
    image: eclipsebasyx/aas-server:1.1.0-SNAPSHOT
    container_name: aas
    ports:
      - 4001:4001
    environment:
        - BaSyxAAS_registry.path=http://registry:4000/registry/
        - BaSyxAAS_aas.backend=InMemory
        - BaSyxContext_contextPath=/aasServer
        - BaSyxContext_contextPort=4001
        - BaSyxAAS_aas.source=aasx/01_Festo.aasx
        - WAITING_FOR=[{"host":"registry","port":"4000"}]
